name: "Target workflow"
run-name: ${{ inputs.distinct_id && inputs.distinct_id || 'N/A' }}

on:
  workflow_dispatch:
    inputs:
      target_input:
        description: 'Target input'
        type: string
        required: false
      distinct_id:
        description: 'Distinct ID'
        required: false

jobs:
  target-workflow:
    runs-on: [ ubuntu-22.04 ]
    # secrets: inherit
    steps:
      - name: Sleep and printout
        run: |
          echo "Target input: ${{ github.event.inputs.target_input }}"
          sleep 30
          echo "Done sleeping"

